# Generated by Django 5.0.1 on 2024-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apiuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
